[package]
name = "timeseries-cli"
version = "0.2.0"
edition = "2021"
description = "Generate a series of timestamps between two bounds."
license = "BSD-3-Clause"

[[bin]]
name = "timeseries"
path = "src/main.rs"

[dependencies]
chrono = "0.4"
structopt = "0.3"
